# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app
# setting instance class doesn't make much change in flexible environments since in flexible we create our own instance class with
# the customized resources needed for our app
#instance_class: F4

runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "3.10"
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 6

resources:
  cpu: 1
  memory_gb: 1.5
  disk_size_gb: 20 

readiness_check:
  app_start_timeout_sec: 1800





